var P8CONFIG = {
	url: 'http://nw4.php168.net/yuanxi/yuanxi74',
	RESOURCE: 'http://nw4.php168.net/yuanxi/yuanxi74',
	language: 'zh-cn',
	controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php',
	U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php',
	cookie_prefix: 'HfYO_',
	cookie_path: '/',
	base_domain: '',
	URI: {
		'ask': {'': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/ask',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/ask',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/ask'},
			'answer': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/ask/modules/answer',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/ask/answer',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/ask/answer'},
			'category': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/ask/modules/category',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/ask/category',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/ask/category'},
			'item': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/ask/modules/item',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/ask/item',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/ask/item'},
			'member': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/ask/modules/member',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/ask/member',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/ask/member'}
		},
		'cms': {'': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/cms',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/cms',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/cms'},
			'assist_category': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/cms/modules/assist_category',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/cms/assist_category',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/cms/assist_category'},
			'category': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/cms/modules/category',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/cms/category',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/cms/category'},
			'item': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/cms/modules/item',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/cms/item',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/cms/item'},
			'model': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/cms/modules/model',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/cms/model',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/cms/model'},
			'statistic': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/cms/modules/statistic',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/cms/statistic',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/cms/statistic'}
		},
		core: {'': {url: 'http://nw4.php168.net/yuanxi/yuanxi74',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php'},
			'46': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/46',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/46',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/46'},
			'cluster': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/cluster',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/cluster',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/cluster'},
			'credit': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/credit',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/credit',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/credit'},
			'crontab': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/crontab',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/crontab',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/crontab'},
			'cservice': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/cservice',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/cservice',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/cservice'},
			'dbm': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/dbm',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/dbm',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/dbm'},
			'discuzx': {url: 'http://www.xxx.com',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/discuzx',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/discuzx'},
			'forms': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/forms',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/forms',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/forms'},
			'friendlink': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/friendlink',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/friendlink',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/friendlink'},
			'guestbook': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/guestbook',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/guestbook',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/guestbook'},
			'interview': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/interview',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/interview',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/interview'},
			'label': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/label',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/label',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/label'},
			'letter': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/letter',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/letter',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/letter'},
			'mail': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/mail',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/mail',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/mail'},
			'member': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/member',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/member',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/member'},
			'message': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/message',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/message',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/message'},
			'notify': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/notify',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/notify',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/notify'},
			'opinion': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/opinion',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/opinion',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/opinion'},
			'page': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/page',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/page',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/page'},
			'pay': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/pay',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/pay',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/pay'},
			'role': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/role',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/role',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/role'},
			'shortcutsms': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/shortcutsms',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/shortcutsms',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/shortcutsms'},
			'sms': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/sms',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/sms',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/sms'},
			'special': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/special',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/special',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/special'},
			'spider': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/spider',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/spider',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/spider'},
			'survey': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/survey',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/survey',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/survey'},
			'uchome': {url: 'http://www.xxx.com',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/uchome',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/uchome'},
			'uploader': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/uploader',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/uploader',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/uploader'},
			'vote': {url: 'http://nw4.php168.net/yuanxi/yuanxi74/modules/vote',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/vote',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/vote'},
			'xspace': {url: '',controller: 'http://nw4.php168.net/yuanxi/yuanxi74/index.php/xspace',U_controller: 'http://nw4.php168.net/yuanxi/yuanxi74/u.php/xspace'}
		}
	}
};