Ext.define('manage.model.newactivity_plan.Newactivity_plan',{
	extend:'Ext.data.Model',
	fields:['id','name','theme','type','school_id','school_name','address','stages','f_id','category','student_amount','need_type','position','teacher_amount','use_car','pre_start_date','change_describe'
	        ,'pre_end_date','need_describe','planId','ap_name','ae_name','salerId','saler_name','create_time','status','saler_submit_date','states','saler_contract_date',
	        'xs_f_id','xs_f_name','chfa_f_id','chfa_f_name','chfa_f_date','pause','chhd_f_id','chjw_f_name','chjw_f_id','chhd_f_name','confirm_start_date','confirm_end_date','plan_finish_date',
	        'executeId','charger_finish_date','final_start_date','final_end_date','cdbg_f_name','cdbg_f_id','final_execute_number','yjya_f_id','yjya_f_name','base_name','base_address',
	        'hdxz_f_id','hdxz_f_name','fkjg_f_id','fkjg_f_name','zxbz_f_id','zxbz_f_name','person_number','activitymanager','orderterminate_date','contract_number','start_execute_date','end_execute_date'
		]
});